[window]
dynamic_title = true
opacity = 0.87

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 5
y = 0

[cursor]
blink_interval = 400
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[scrolling]
history = 100000
multiplier = 5

[env]
TERM = "xterm-256color"

[font]
size = 11.0
offset = { x = 0, y = 4 }
normal = { family = "Hack Nerd Font", style="Regular" }
bold = { family = "Hack Nerd Font", style="Bold" }
italic = { family = "Hack Nerd Font", style="Italic" }
bold_italic = { family = "Hack Nerd Font", style="Bold Italic" }

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux a -t 0 || tmux -u"] }
